version: '3.8'

services:
  motorcycleforum.web:
    build:
      context: .
      dockerfile: MotorcycleForum.Web/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
